openapi: 3.0.0
info:
  title: hr api
  description: blah an api that allows users to obtain existing information of employeees
    or post info of new employees
  termsOfService: https://smartbear.com/terms-of-use
  contact:
    name: thunder
    url: thunder.com
    email: thunder@gmail.com
  license:
    name: thunder
    url: https://licence.thunder.com
  version: 2.0.0
servers:
- url: https://dev.foo.com/v1
  description: Dev server
- url: https://prod.foo.com/v1
  description: Prod server
paths:
  /employees:
    get:
      description: Obtain info about employees from the HR database
      operationId: allemp
      parameters:
      - name: bodyLimit
        in: query
        description: The amount of employees returned
        required: false
        style: form
        explode: true
        schema:
          maximum: 20
          minimum: 10
          type: integer
          example: 15
      - name: pageLimit
        in: query
        description: The pages to return employees info
        required: false
        style: form
        explode: true
        schema:
          maximum: 5
          minimum: 1
          type: integer
          example: 2
      responses:
        "200":
          description: Successful pull of employee info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
    post:
      description: create a new employee in the database
      operationId: showemp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
          application/xml:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        "200":
          description: Successfully created a new employee
  /employee/{id}:
    get:
      description: Obtain information about specific employee
      operationId: empbyid
      parameters:
      - name: id
        in: path
        description: the id of the employee
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 54
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
            application/xml:
              schema:
                $ref: '#/components/schemas/Employee'
components:
  schemas:
    Employees:
      type: array
      description: Array of employee info
      items:
        $ref: '#/components/schemas/Employee'
    Employee:
      properties:
        id:
          type: integer
          example: 4
        employee name:
          type: string
          example: Ryan Pinkham
        employee title:
          type: string
          example: Market Manager
      description: Model containing employee info
